# Generated by Django 3.1.3 on 2020-11-23 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='optometria.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Secretaría'), (2, 'Profesional médico'), (3, 'Ventas'), (4, 'Taller'), (5, 'Gerencia')], primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta de crédito'), (2, 'Tarjeta de Débito'), (3, 'Billetera virtual'), (4, 'Efectivo')], default=2)),
                ('nombre', models.CharField(max_length=50)),
                ('lente', models.PositiveSmallIntegerField(choices=[(1, 'Lejos'), (2, 'Cerca'), (3, 'Izquierda'), (4, 'Derecha')], default=None)),
                ('armazon', models.BooleanField(default=False)),
                ('pedido', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Pedido'), (2, 'Taller'), (4, 'Finalizado')], default=1)),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='optometria.paciente')),
                ('producto', models.ManyToManyField(to='optometria.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optometria.tipodocumento'),
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(default='')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optometria.paciente')),
            ],
        ),
    ]
